[package]
name = "histogram"
version = "0.1.0"
authors = ["Wojciech Dudczak <wojciech.dudczak@gpw.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
regex = "1"
hdrhistogram = "6.0"
