[package]
name = "histogram"
version = "0.0.1"
authors = ["Wojciech Dudczak <wojciech.dudczak@gpw.pl>"]
edition = "2018"

#[lib]
#name = "core"
#path = "src/mod.rs"

[[bin]]
name = "histogram_r"
path = "src/main.rs"

[dependencies]
getopts = "0.2"
regex = "1"
hdrhistogram = "6.0"
